- name: Setup proxy for apt
  blockinfile:
    path: /etc/apt/apt.conf.d/proxy.conf
    create: yes
    block: |
      Acquire::http::Proxy "http://{{ jumpbox }}:8080/";
      Acquire::https::Proxy "http://{{ jumpbox }}:8080/";

- name: Wait for unattended upgrades
  raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true

- name: Install packages
  apt:
    name: "{{ packages }}"
    force_apt_get: yes
    update_cache: no
    dpkg_options: 'force-confold,force-confdef'
  ignore_errors: false
  vars:
    packages:
    - jq
