- name: Copy manifest
  copy:
    src: manifests/
    dest: "/home/{{ admin }}/k8s/nexus_oss"
    owner: "{{ admin }}"
  when: manifests.stat.exists == False or (force is defined and force | lower == "yes")

- name: Copy templated ingress
  template:
    src: manifests/ingress.yaml
    dest: "/home/{{ admin }}/k8s/nexus_oss"
    owner: "{{ admin }}"
  when: manifests.stat.exists == False or (force is defined and force | lower == "yes")
