- name: Set static mountd to port 32767
  replace:
    path: /etc/default/nfs-kernel-server
    regexp: 'manage-gids'
    replace: 'port 32767' 

# - name: Set NFS Callback Support
#   template:
#     src: nfs-local.conf
#     dest: /etc/modprobe.d/nfs-local.conf
#     owner: root
#     group: root

- name: Set NFS NLM TCP Port
  sysctl:
    name: fs.nfs.nlm_tcpport
    value: '32768'
    sysctl_file: /etc/sysctl.conf
    reload: no

- name: Set NFS NLM UDP Port
  sysctl:
    name: fs.nfs.nlm_udpport
    value: '32768'
    sysctl_file: /etc/sysctl.conf
    reload: yes
