- name: Wait for unattended upgrades
  raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true

- name: Install packages
  apt:
    name: "{{ packages }}"
    force_apt_get: yes
    update_cache: no
    dpkg_options: 'force-confold,force-confdef'
  ignore_errors: false
  vars:
    packages:
    - nfs-kernel-server
    - nfs-common

- name: Set static mountd to port 32767
  replace:
    path: /etc/default/nfs-kernel-server
    regexp: 'manage-gids'
    replace: 'port 32767' 

- name: Set NFS Callback Support
  template:
    src: nfs-local.conf
    dest: /etc/modprobe.d/nfs-local.conf
    owner: root
    group: root

- name: Set NFS NLM TCP Port
  sysctl:
    name: fs.nfs.nlm_tcpport
    value: '32768'
    sysctl_file: /etc/sysctl.conf
    reload: no

- name: Set NFS NLM UDP Port
  sysctl:
    name: fs.nfs.nlm_udpport
    value: '32768'
    sysctl_file: /etc/sysctl.conf
    reload: yes

- name: Get UUID for datadisk
  shell: |
    blkid | grep /dev/sdc1 | awk '{print $2}' | sed -e 's/UUID="\(.*\)\"/\1/'
  register: uuid

- name: Show UUID
  debug:
    msg: "UUID is {{ uuid.stdout }}"

- name: Make mount point
  file:
    path: /datadrive
    state: directory
    mode: '0777'

- name: Configure datadrive in fstab
  mount: 
    path: /datadrive
    src: UUID={{ uuid.stdout }}
    fstype: ext4
    opts: defaults,nofail
    state: mounted

- name: Make NFS share
  file:
    path: /datadrive/export
    state: directory
    mode: '0777'

- name: Make NFS share
  file:
    path: /datadrive/export
    state: directory
    mode: '0777'

- name: Add entry to NFS exports for k8s-master
  lineinfile:
    path: /etc/exports
    line: /datadrive/export {{ hostvars[item]['ansible_facts']['eth0']['ipv4']['address'] }}(rw,async,no_root_squash,insecure,fsid=0,crossmnt,no_subtree_check)
  with_items:
    - "{{ groups['all'] }}"
  notify: "restart NFS Server"

# - name: Restart NFS server
#   service:
#     name: nfs-kernel-server
#     state: restarted