- import_tasks: packages.yml
- import_tasks: configuration.yml
- import_tasks: mount.yml
- import_tasks: share.yml
- name: Reboot NFS Server
  reboot:
    reboot_timeout: 600
  when: reloaded_nfs.changed