- name: Get UUID for datadisk
  shell: |
    blkid | grep /dev/sdc1 | awk '{print $2}' | sed -e 's/UUID="\(.*\)\"/\1/'
  register: uuid

- name: Show UUID
  debug:
    msg: "UUID is {{ uuid.stdout }}"

- name: Make mount point
  file:
    path: /datadrive
    state: directory
    mode: '0777'

- name: Configure datadrive in fstab
  mount: 
    path: /datadrive
    src: UUID={{ uuid.stdout }}
    fstype: ext4
    opts: defaults,nofail
    state: mounted

