- name: Setup proxy for apt
  blockinfile:
    path: /etc/apt/apt.conf.d/proxy.conf
    create: yes
    block: |
      Acquire::http::Proxy "http://{{ jumpbox }}:8080/";
      Acquire::https::Proxy "http://{{ jumpbox }}:8080/";
