- name: Create namespace
  shell: |
    kubectl create namespace cert-manager

- name: Fetch and apply cert-manager
  shell: |
    kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.13.1/cert-manager.yaml

- name: Make sure cert-manager is running (up to 10min.)
  shell: kubectl get pods --namespace cert-manager --field-selector status.phase!="Running"
  register: result
  until: result.stderr.find("No resources found") != -1
  retries: 60
  delay: 10
