---
- hosts:
  - master
  - workers
  become: true
  any_errors_fatal: true
  tasks:
    - import_role:
        name: docker_engine
      tags: docker_engine
    - import_role:
        name: docker_compose
      tags: docker_compose
