---
# Setup hosts, update packages, set date & time and
# disable swap.
- hosts: all
  become: true
  any_errors_fatal: true
  tasks:
    - import_role:
        name: general_server
      tags: general_server
