- name: Copy manifests
  copy:
    src: manifests/
    dest: "/home/{{ admin }}/k8s/jenkins"
    owner: "{{ admin }}"
  when: manifests.stat.exists == False or (force is defined and force | lower == "yes")

- name: Copy getcreds script
  copy:
    src: scripts/getcreds.sh
    dest: "/home/{{ admin }}/k8s/jenkins/"
    owner: "{{ admin }}"
    mode: '0755'
  when: manifests.stat.exists == False or (force is defined and force | lower == "yes")

- name: Copy templated namespace
  template:
    src: manifests/namespace.yaml
    dest: "/home/{{ admin }}/k8s/jenkins"
    owner: "{{ admin }}"
  when: manifests.stat.exists == False or (force is defined and force | lower == "yes")

- name: Copy templated Docker config
  template:
    src: manifests/docker-daemon.yaml
    dest: "/home/{{ admin }}/k8s/jenkins"
    owner: "{{ admin }}"
  when: manifests.stat.exists == False or (force is defined and force | lower == "yes")

- name: Copy templated jenkins-docker deploy
  template:
    src: manifests/jenkins-docker.yaml
    dest: "/home/{{ admin }}/k8s/jenkins"
    owner: "{{ admin }}"
  when: manifests.stat.exists == False or (force is defined and force | lower == "yes")

- name: Copy templated sonarqube deploy
  template:
    src: manifests/sonarqube.yaml
    dest: "/home/{{ admin }}/k8s/jenkins"
    owner: "{{ admin }}"
  when: manifests.stat.exists == False or (force is defined and force | lower == "yes")

- name: Copy templated jenkins ingress
  template:
    src: manifests/jenkins-ingress.yaml
    dest: "/home/{{ admin }}/k8s/jenkins"
    owner: "{{ admin }}"
  when: manifests.stat.exists == False or (force is defined and force | lower == "yes")

- name: Copy templated sonarqube ingress
  template:
    src: manifests/sonarqube-ingress.yaml
    dest: "/home/{{ admin }}/k8s/jenkins"
    owner: "{{ admin }}"
  when: manifests.stat.exists == False or (force is defined and force | lower == "yes")
